### ISSUE TITLE
Sampling issues for uniform distributions with floating-point values

### ISSUE THREAD

**Issue by cloudbopper** [probcomp/fast-loaded-dice-roller#4]
Using a uniform distribution with floating-point values seems to result in only 0 or 1 values while sampling.

```
from fldr import fldrf_preprocess
from fldr import fldr_sample
x = fldrf_preprocess([0.1 for _ in range(10)])
print([fldr_sample(x) for _ in range(20)])
```
[0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1]

**Comment by fsaad** [comment]
Thank you for the ticket. Could you try using the the C-style floating-point preprocessing algorithm by changing the import line to:
```python
from fldr.fldrf import fldr_preprocess_float_c as fldrf_preprocess
```

The issue in this ticket is due to a bug in what seems to be the Python 3 `math` library
```
>>> from math import log2
>>> ceil(log2(36028797018963970))
55
```

whereas [true answer](https://www.wolframalpha.com/input/?i=Ceil%5BLog%5B2%2C+36028797018963970%5D%5D) should be 56

**Comment by cloudbopper** [comment]
Thanks, verified that the alternative produces sensible sampled values.

**Comment by peteroupc** [comment]
An alternative to `ceil(log2(x))` is `(x-1).bit_length()` (which works for all integers 1 or greater).

**Comment by fsaad** [comment]
Thanks @peteroupc, I have incorporated your suggestion in 2fb32e94a04c744c86aa4cb54b3ee0259894e777
