### ISSUE TITLE
Sampling with floating-point distributions seems to be significantly slower

### ISSUE THREAD

**Issue by cloudbopper** [probcomp/fast-loaded-dice-roller#5]
Not sure if this is expected or if it's a bug.

```
python -m timeit -s "from fldr import fldr_preprocess; from fldr import fldr_sample; l = range(10000); x = fldr_preprocess([1 for _ in l])" "fldr_sample(x)"
```

50000 loops, best of 5: 6 usec per loop

```
python -m timeit -s "from fldr import fldrf_preprocess; from fldr import fldr_sample; l = range(10000); x = fldrf_preprocess([1/len(l) for _ in l])" "fldr_sample(x)"
```
50 loops, best of 5: 5.1 msec per loop

**Comment by fsaad** [comment]
Thanks for the runtime measurements.  These numbers are in line with expectation for preprocessing floats, since the floating-point algorithm (which itself is not very optimized) is significantly more expensive than the integer arithmetic algorithm.

The [implementation in C](https://github.com/probcomp/fast-loaded-dice-roller/tree/master/src/c) is much faster.  We should consider using e.g., Cython to create a Python API.

**Comment by cloudbopper** [comment]
Ok, thanks.
FYI the runtime measurements only include sampling, not preprocessing. I also noted that using the alternative floating-point algorithm mentioned in #4 resulted in runtimes much more comparable to the integer algorithm.
```
python -m timeit -s "from fldr.fldrf import fldr_preprocess_float_c as fldrf_preprocess; from fldr import fldr_sample; l = range(10000); x = fldrf_preprocess([1/len(l) for _ in l])" "fldr_sample(x)"
```
50000 loops, best of 5: 7.16 usec per loop

Thanks again for the great work.

**Comment by fsaad** [comment]
Thanks again for confirming.  I will change the default implementation to use the alternative preprocessing algorithm in light of #4 and #5.

> FYI the runtime measurements only include sampling, not preprocessing. 
Good point, I missed the fact that your timeit script uses `-s` for "setup".
